---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: statistics-deployment
spec:
  selector:
    matchLabels:
      app: statistics # 选择这个指定标签执行
  replicas: 2 # 运行pod数量
  template:
    metadata:
      labels:
        app: statistics # 标签
    spec:
      containers:
      - name: statistics
        image: openim/statistics:v2.0.10
        ports:
        - containerPort: 10180
        volumeMounts:
          - name: config
            mountPath: /Open-IM-Server/config
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: config
  strategy: #更新策略
    type: RollingUpdate # 滚动更新
